### PR TITLE
rewrite to python3

### PR DESCRIPTION
**Pull request by torrottum**
Created a helper function `send_sock` which encodes to byte object before sending over the socket and prints the command
This is because python3 sockets can only send byte objects (I think).

At places where data are received from the socket, it's decoded as well.

I've also rewritten the string string formatting from the `"%s" % (var)` way of doing things to `"{0}".format(var)`

### CODE REVIEW

**Review by svimanet — APPROVED** [review]
very nice yes yes

**Comment by torrottum** [comment]
Nice yes
Very nice
Love your bot, yes

**Comment by svimanet** [comment]
Yes thenk you forgot to change urban module to py3 but very nice bot and work thenks!


-------- Original Message --------
Subject: Re: [svimanet/IRC-Bob] rewrite to python3 (#5)
From: Tor Røttum
To: svimanet/IRC-Bob
CC: Eirik ,State change

Nice yes
Very nice
Love your bot, yes

**Comment by torrottum** [comment]
Nice yes,
Oh, did I forget? That is bad programming from me, yes? 
I will become better at programming, yes
Because I really like programming yes
You are great person, yes

**Pull request merged**
